import {
  type HistoricalSourceRow,
  type HistoricalReconciliationSummary,
  type MigrationClassification,
  type MigrationPaymentMode,
  type MigrationRowStatus,
} from '../types/migration'
import { type Transaction, type Account } from '../types/accounting'
import { validateDoubleEntry, generateNextVoucherNo } from './accountingEngine'

export const SOURCE_DOCUMENT_NAME = 'Tribal Harvest Day Book Register as on 30 March 2026'
export const MIGRATION_BATCH_ID = 'THMCS-HIST-2025-26'

export const SOURCE_STATED_TOTALS = {
  receipts: 135531.0,
  payments: 80120.87,
  closingBalance: 55410.13,
  grandTotal: 135531.0,
}

/* ── 49 Historical Rows exactly as extracted from Source PDF ── */
export const rawHistoricalRows: Omit<HistoricalSourceRow, 'id'>[] = [
  // ── PAGE 1: APRIL 2025 ──
  {
    slno: 1,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 1,
    sourceDate: '01-04-2025',
    sourceParticular: 'Share Capital',
    sourceReceipt: 105000,
    sourcePayment: null,
    sourceAmount: 105000,
    classification: 'SHARE_CAPITAL',
    accountId: 'acc_share_capital',
    accountName: 'Share Capital',
    accountCode: '3010',
    paymentMode: 'UNKNOWN',
    memberId: 'UNALLOCATED_HISTORICAL',
    memberName: 'Unallocated Historical Member',
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: [
      'Historical Share Capital entry of ₹105,000.',
      'Member-level allocation unstated in source Day Book. Classify as Equity (Code 3010), not income.',
      'Payment mode unstated in Day Book (Part 7: default UNKNOWN).',
    ],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 2,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 2,
    sourceDate: '01-04-2025',
    sourceParticular: 'Membership Fees',
    sourceReceipt: 3200,
    sourcePayment: null,
    sourceAmount: 3200,
    classification: 'MEMBERSHIP_FEE',
    accountId: 'acc_adm_fee',
    accountName: 'Membership / Admission Fees',
    accountCode: '4020',
    paymentMode: 'UNKNOWN',
    memberId: 'UNALLOCATED_HISTORICAL',
    memberName: 'Unallocated Historical Member',
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: [
      'Historical Membership Fees of ₹3,200.',
      'Member breakdown unstated in source Day Book. Do not create artificial member transactions (Part 9).',
      'Payment mode unstated in Day Book (Part 7: default UNKNOWN).',
    ],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 3,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 3,
    sourceDate: '05-04-2025',
    sourceParticular: 'Meeting Expenses',
    sourceReceipt: null,
    sourcePayment: 1000,
    sourceAmount: 1000,
    classification: 'MEETING_BOD',
    accountId: 'acc_meeting',
    accountName: 'Meeting & BOD Expenses',
    accountCode: '5060',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book (Part 7).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 4,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 4,
    sourceDate: '04-05-2026', // Critical Part 15 Anomaly
    sourceParticular: 'Typing and printing',
    sourceReceipt: null,
    sourcePayment: 120,
    sourceAmount: 120,
    classification: 'PRINTING_PACKAGING',
    accountId: 'acc_stationery',
    accountName: 'Printing & Stationery',
    accountCode: '5080',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    dateWarning: true,
    reviewNotes: [
      '⚠ DATE REQUIRES VERIFICATION: Source records "04-05-2026". Probable historical typo for 04-05-2025.',
      'Preserved source date as stated per Part 15; requires accountant approval to correct.',
      'Payment mode unstated in source Day Book.',
    ],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── MAY 2025 ──
  {
    slno: 5,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 5,
    sourceDate: '12-05-2025',
    sourceParticular: 'Admin and office ( Seal & Pad)',
    sourceReceipt: null,
    sourcePayment: 4000,
    sourceAmount: 4000,
    classification: 'ADMINISTRATION',
    accountId: 'acc_admin_office',
    accountName: 'Admin and Office (Seal & Pad)',
    accountCode: '5070',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 6,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 6,
    sourceDate: '13-05-2025',
    sourceParticular: 'Register',
    sourceReceipt: null,
    sourcePayment: 320,
    sourceAmount: 320,
    classification: 'PRINTING_PACKAGING',
    accountId: 'acc_stationery',
    accountName: 'Printing & Stationery',
    accountCode: '5080',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── JUNE 2025 ──
  {
    slno: 7,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 7,
    sourceDate: '20-06-2025',
    sourceParticular: 'Sale Deed House rent agreement',
    sourceReceipt: null,
    sourcePayment: 1000,
    sourceAmount: 1000,
    classification: 'ADMINISTRATION',
    accountId: 'acc_rent_doc',
    accountName: 'Sale Deed House Rent Agreement & Documentation',
    accountCode: '5090',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 8,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 8,
    sourceDate: '20-06-2025',
    sourceParticular: 'Documentation',
    sourceReceipt: null,
    sourcePayment: 300,
    sourceAmount: 300,
    classification: 'ADMINISTRATION',
    accountId: 'acc_rent_doc',
    accountName: 'Sale Deed House Rent Agreement & Documentation',
    accountCode: '5090',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── JULY 2025 ──
  {
    slno: 9,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 9,
    sourceDate: '01-07-2025',
    sourceParticular: 'FSSAI Registration paid online',
    sourceReceipt: null,
    sourcePayment: 3400,
    sourceAmount: 3400,
    classification: 'REGISTRATION_GOV',
    accountId: 'acc_license',
    accountName: 'Trade License & Legal Formalities (FSSAI)',
    accountCode: '5100',
    paymentMode: 'UPI_ONLINE', // Explicitly stated in source: "paid online"
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'MAPPED',
    reviewNotes: ['Source specifies "paid online" -> Mapped to UPI / ONLINE (Part 7).'],
    paymentModeWarning: false,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 10,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 10,
    sourceDate: '02-07-2025',
    sourceParticular: 'Meeting Expenses',
    sourceReceipt: null,
    sourcePayment: 1000,
    sourceAmount: 1000,
    classification: 'MEETING_BOD',
    accountId: 'acc_meeting',
    accountName: 'Meeting & BOD Expenses',
    accountCode: '5060',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 11,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 11,
    sourceDate: '27-07-2025',
    sourceParticular: 'Meeting & BOD Expenses',
    sourceReceipt: null,
    sourcePayment: 700,
    sourceAmount: 700,
    classification: 'MEETING_BOD',
    accountId: 'acc_meeting',
    accountName: 'Meeting & BOD Expenses',
    accountCode: '5060',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 12,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 12,
    sourceDate: '30-07-2025',
    sourceParticular: 'Purchase – Restokart',
    sourceReceipt: null,
    sourcePayment: 2566.18,
    sourceAmount: 2566.18,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement',
    accountName: 'Supplier Procurements (Restokart)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: [
      'Procurement source: Restokart (Part 11).',
      'Stock protection (Part 26): Financial amount importable; stock physical quantities unstated in Day Book.',
      'Payment mode unstated in source Day Book.',
    ],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── AUGUST 2025 ──
  {
    slno: 13,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 13,
    sourceDate: '04-08-2025',
    sourceParticular: 'Purchase – Swiss',
    sourceReceipt: null,
    sourcePayment: 250,
    sourceAmount: 250,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement_swiss',
    accountName: 'Supplier Procurements (Swiss)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Swiss (Part 11). Stock quantities unstated (Part 26). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 14,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 14,
    sourceDate: '10-08-2025',
    sourceParticular: 'BOD Expenses',
    sourceReceipt: null,
    sourcePayment: 300,
    sourceAmount: 300,
    classification: 'MEETING_BOD',
    accountId: 'acc_meeting',
    accountName: 'Meeting & BOD Expenses',
    accountCode: '5060',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 15,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 15,
    sourceDate: '13-08-2025',
    sourceParticular: 'Purchase – Swiss',
    sourceReceipt: null,
    sourcePayment: 1805.40,
    sourceAmount: 1805.40,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement_swiss',
    accountName: 'Supplier Procurements (Swiss)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Swiss. Stock quantities unstated. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 16,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 16,
    sourceDate: '15-08-2025',
    sourceParticular: 'BOD Expenses',
    sourceReceipt: null,
    sourcePayment: 400,
    sourceAmount: 400,
    classification: 'MEETING_BOD',
    accountId: 'acc_meeting',
    accountName: 'Meeting & BOD Expenses',
    accountCode: '5060',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 17,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 17,
    sourceDate: '20-08-2025',
    sourceParticular: 'Purchase – Restokart',
    sourceReceipt: null,
    sourcePayment: 2483.04,
    sourceAmount: 2483.04,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement',
    accountName: 'Supplier Procurements (Restokart)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Restokart. Stock quantities unstated. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 18,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 18,
    sourceDate: '21-08-2025',
    sourceParticular: 'Purchase – Aumni',
    sourceReceipt: null,
    sourcePayment: 847,
    sourceAmount: 847,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement_aumni',
    accountName: 'Supplier Procurements (Aumni)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Aumni. Stock quantities unstated. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 19,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 19,
    sourceDate: '29-08-2025',
    sourceParticular: 'Meeting Expenses',
    sourceReceipt: null,
    sourcePayment: 800,
    sourceAmount: 800,
    classification: 'MEETING_BOD',
    accountId: 'acc_meeting',
    accountName: 'Meeting & BOD Expenses',
    accountCode: '5060',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 20,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 20,
    sourceDate: '29-08-2025',
    sourceParticular: 'Purchase – Swiss',
    sourceReceipt: null,
    sourcePayment: 3943.56,
    sourceAmount: 3943.56,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement_swiss',
    accountName: 'Supplier Procurements (Swiss)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Swiss. Stock quantities unstated. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── SEPTEMBER 2025 ──
  {
    slno: 21,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 21,
    sourceDate: '01-09-2025',
    sourceParticular: 'Purchase – Restokart',
    sourceReceipt: null,
    sourcePayment: 1923.37,
    sourceAmount: 1923.37,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement',
    accountName: 'Supplier Procurements (Restokart)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Restokart. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 22,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 22,
    sourceDate: '01-09-2025',
    sourceParticular: 'Raw Materials Purchase for ( 200 Bastenga)',
    sourceReceipt: null,
    sourcePayment: 5000,
    sourceAmount: 5000,
    classification: 'RAW_MATERIAL',
    accountId: 'acc_inv_raw',
    accountName: 'Inventory – Raw Materials / Feeds',
    accountCode: '1050',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Raw Materials for 200 Bastenga',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Raw materials for 200 Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 23,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 23,
    sourceDate: '01-09-2025',
    sourceParticular: 'Labour & Operating Expenses',
    sourceReceipt: null,
    sourcePayment: 2966,
    sourceAmount: 2966,
    classification: 'LABOUR',
    accountId: 'acc_labour',
    accountName: 'Labour & Shed Maintenance',
    accountCode: '5040',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Production labour and operating costs (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 24,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 24,
    sourceDate: '01-09-2025',
    sourceParticular: 'Printing & Packaging',
    sourceReceipt: null,
    sourcePayment: 2400,
    sourceAmount: 2400,
    classification: 'PRINTING_PACKAGING',
    accountId: 'acc_stationery',
    accountName: 'Printing & Stationery',
    accountCode: '5080',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Packaging for Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 25,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 25,
    sourceDate: '07-09-2025',
    sourceParticular: 'Bastenga Launch',
    sourceReceipt: null,
    sourcePayment: 1000,
    sourceAmount: 1000,
    classification: 'PROJECT_EXPENDITURE',
    accountId: 'acc_promotional',
    accountName: 'Promotional & Launch Expenses',
    accountCode: '5110',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Product launch event expenditure. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 26,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 26,
    sourceDate: '15-09-2025',
    sourceParticular: 'Printing of Cahs memo',
    sourceReceipt: null,
    sourcePayment: 7000,
    sourceAmount: 7000,
    classification: 'PRINTING_PACKAGING',
    accountId: 'acc_stationery',
    accountName: 'Printing & Stationery',
    accountCode: '5080',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Printing of cash memo books. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 27,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 1,
    sourceRowNumber: 27,
    sourceDate: '30-09-2025',
    sourceParticular: 'Bastenga Sales (30 packets)',
    sourceReceipt: 2050,
    sourcePayment: null,
    sourceAmount: 2050,
    classification: 'SALES',
    accountId: 'acc_sales',
    accountName: 'Product & Livestock Sales',
    accountCode: '4010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Bastenga Finished Packets (30)',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Individual Bastenga sales batch (30 pkts). Payment mode UNKNOWN (Part 10).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── PAGE 2: OCTOBER 2025 ──
  {
    slno: 28,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 28,
    sourceDate: '03-10-2025',
    sourceParticular: 'Meeting Expenses',
    sourceReceipt: null,
    sourcePayment: 2000,
    sourceAmount: 2000,
    classification: 'MEETING_BOD',
    accountId: 'acc_meeting',
    accountName: 'Meeting & BOD Expenses',
    accountCode: '5060',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Payment mode unstated in source Day Book.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 29,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 29,
    sourceDate: '04-10-2025',
    sourceParticular: 'Raw Materials Purchase for ( 200 Bastenga)',
    sourceReceipt: null,
    sourcePayment: 5000,
    sourceAmount: 5000,
    classification: 'RAW_MATERIAL',
    accountId: 'acc_inv_raw',
    accountName: 'Inventory – Raw Materials / Feeds',
    accountCode: '1050',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Raw Materials for 200 Bastenga',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Raw materials for 200 Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 30,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 30,
    sourceDate: '04-10-2025',
    sourceParticular: 'Labour & Operating Expenses',
    sourceReceipt: null,
    sourcePayment: 2966,
    sourceAmount: 2966,
    classification: 'LABOUR',
    accountId: 'acc_labour',
    accountName: 'Labour & Shed Maintenance',
    accountCode: '5040',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Production labour and operating costs (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 31,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 31,
    sourceDate: '04-10-2025',
    sourceParticular: 'Printing & Packaging',
    sourceReceipt: null,
    sourcePayment: 2400,
    sourceAmount: 2400,
    classification: 'PRINTING_PACKAGING',
    accountId: 'acc_stationery',
    accountName: 'Printing & Stationery',
    accountCode: '5080',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Packaging for Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 32,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 32,
    sourceDate: '04-10-2025',
    sourceParticular: 'Purchase – Aumni',
    sourceReceipt: null,
    sourcePayment: 1247,
    sourceAmount: 1247,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement_aumni',
    accountName: 'Supplier Procurements (Aumni)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Aumni. Stock quantities unstated. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 33,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 33,
    sourceDate: '25-10-2025',
    sourceParticular: 'Purchase – Restokart',
    sourceReceipt: null,
    sourcePayment: 2909.12,
    sourceAmount: 2909.12,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement',
    accountName: 'Supplier Procurements (Restokart)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Restokart. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 34,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 34,
    sourceDate: '26-10-2025',
    sourceParticular: 'Purchase – Swiss',
    sourceReceipt: null,
    sourcePayment: 4708.20,
    sourceAmount: 4708.20,
    classification: 'PROCUREMENT',
    accountId: 'acc_procurement_swiss',
    accountName: 'Supplier Procurements (Swiss)',
    accountCode: '5010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: 'UNSPECIFIED_HISTORICAL_QUANTITY',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Procurement source: Swiss. Stock quantities unstated. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 35,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 35,
    sourceDate: '31-10-2025',
    sourceParticular: 'Bastenga Sales (40 packets)',
    sourceReceipt: 2733,
    sourcePayment: null,
    sourceAmount: 2733,
    classification: 'SALES',
    accountId: 'acc_sales',
    accountName: 'Product & Livestock Sales',
    accountCode: '4010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Bastenga Finished Packets (40)',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Individual Bastenga sales batch (40 pkts). Payment mode UNKNOWN (Part 10).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── NOVEMBER 2025 ──
  {
    slno: 36,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 36,
    sourceDate: '14-11-2025',
    sourceParticular: 'Raw Materials Purchase for ( 200 Bastenga)',
    sourceReceipt: null,
    sourcePayment: 5000,
    sourceAmount: 5000,
    classification: 'RAW_MATERIAL',
    accountId: 'acc_inv_raw',
    accountName: 'Inventory – Raw Materials / Feeds',
    accountCode: '1050',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Raw Materials for 200 Bastenga',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Raw materials for 200 Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 37,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 37,
    sourceDate: '14-11-2025',
    sourceParticular: 'Labour & Operating Expenses',
    sourceReceipt: null,
    sourcePayment: 2966,
    sourceAmount: 2966,
    classification: 'LABOUR',
    accountId: 'acc_labour',
    accountName: 'Labour & Shed Maintenance',
    accountCode: '5040',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Production labour and operating costs (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 38,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 38,
    sourceDate: '14-11-2025',
    sourceParticular: 'Printing & Packaging',
    sourceReceipt: null,
    sourcePayment: 2400,
    sourceAmount: 2400,
    classification: 'PRINTING_PACKAGING',
    accountId: 'acc_stationery',
    accountName: 'Printing & Stationery',
    accountCode: '5080',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Packaging for Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 39,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 39,
    sourceDate: '30-11-2025',
    sourceParticular: 'Bastenga Sales (80 packets)',
    sourceReceipt: 5466,
    sourcePayment: null,
    sourceAmount: 5466,
    classification: 'SALES',
    accountId: 'acc_sales',
    accountName: 'Product & Livestock Sales',
    accountCode: '4010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Bastenga Finished Packets (80)',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Individual Bastenga sales batch (80 pkts). Payment mode UNKNOWN (Part 10).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── DECEMBER 2025 ──
  {
    slno: 40,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 40,
    sourceDate: '31-12-2025',
    sourceParticular: 'Bastenga Sales (120 packets)',
    sourceReceipt: 8200,
    sourcePayment: null,
    sourceAmount: 8200,
    classification: 'SALES',
    accountId: 'acc_sales',
    accountName: 'Product & Livestock Sales',
    accountCode: '4010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Bastenga Finished Packets (120)',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Individual Bastenga sales batch (120 pkts). Payment mode UNKNOWN (Part 10).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── JANUARY 2026 ──
  {
    slno: 41,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 41,
    sourceDate: '15-01-2026',
    sourceParticular: 'Anniversary',
    sourceReceipt: null,
    sourcePayment: 3000,
    sourceAmount: 3000,
    classification: 'ADMINISTRATION',
    accountId: 'acc_anniversary',
    accountName: 'Anniversary & Society Events',
    accountCode: '5120',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Society anniversary commemoration expenses. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 42,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 42,
    sourceDate: '31-01-2026',
    sourceParticular: 'Bastenga Sales (50 packets)',
    sourceReceipt: 3416,
    sourcePayment: null,
    sourceAmount: 3416,
    classification: 'SALES',
    accountId: 'acc_sales',
    accountName: 'Product & Livestock Sales',
    accountCode: '4010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Bastenga Finished Packets (50)',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Individual Bastenga sales batch (50 pkts). Payment mode UNKNOWN (Part 10).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── FEBRUARY 2026 ──
  {
    slno: 43,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 43,
    sourceDate: '06-02-2026',
    sourceParticular: 'Raw Materials Purchase for ( 400 Bastenga)',
    sourceReceipt: null,
    sourcePayment: 10000,
    sourceAmount: 10000,
    classification: 'RAW_MATERIAL',
    accountId: 'acc_inv_raw',
    accountName: 'Inventory – Raw Materials / Feeds',
    accountCode: '1050',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Raw Materials for 400 Bastenga',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Raw materials for 400 Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 44,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 44,
    sourceDate: '06-02-2026',
    sourceParticular: 'Operating Cost',
    sourceReceipt: null,
    sourcePayment: 4532,
    sourceAmount: 4532,
    classification: 'LABOUR',
    accountId: 'acc_labour',
    accountName: 'Labour & Shed Maintenance',
    accountCode: '5040',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Production operating cost (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 45,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 45,
    sourceDate: '06-02-2026',
    sourceParticular: 'Printing & Packaging',
    sourceReceipt: null,
    sourcePayment: 4800,
    sourceAmount: 4800,
    classification: 'PRINTING_PACKAGING',
    accountId: 'acc_stationery',
    accountName: 'Printing & Stationery',
    accountCode: '5080',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Packaging for Bastenga production (Part 12). Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 46,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 46,
    sourceDate: '28-02-2026',
    sourceParticular: 'Bastenga Sales (40 packets)',
    sourceReceipt: 2733,
    sourcePayment: null,
    sourceAmount: 2733,
    classification: 'SALES',
    accountId: 'acc_sales',
    accountName: 'Product & Livestock Sales',
    accountCode: '4010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Bastenga Finished Packets (40)',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Individual Bastenga sales batch (40 pkts). Payment mode UNKNOWN (Part 10).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },

  // ── MARCH 2026 ──
  {
    slno: 47,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 47,
    sourceDate: '31-03-2026',
    sourceParticular: 'Bastenga Sales (40 packets)',
    sourceReceipt: 2733,
    sourcePayment: null,
    sourceAmount: 2733,
    classification: 'SALES',
    accountId: 'acc_sales',
    accountName: 'Product & Livestock Sales',
    accountCode: '4010',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: 'BASTENGA_PRODUCTION',
    projectName: 'Bastenga / Food Production',
    stockItem: 'Bastenga Finished Packets (40)',
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Individual Bastenga sales batch (40 pkts). Payment mode UNKNOWN (Part 10).'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 48,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 48,
    sourceDate: '31-03-2026',
    sourceParticular: 'Audit',
    sourceReceipt: null,
    sourcePayment: 300,
    sourceAmount: 300,
    classification: 'AUDIT',
    accountId: 'acc_audit_fee',
    accountName: 'Audit & NSCU Affiliation Fee',
    accountCode: '5130',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Cooperative audit statutory fee. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
  {
    slno: 49,
    sourceDocument: SOURCE_DOCUMENT_NAME,
    sourcePage: 2,
    sourceRowNumber: 49,
    sourceDate: '31-03-2026',
    sourceParticular: 'NSCU',
    sourceReceipt: null,
    sourcePayment: 100,
    sourceAmount: 100,
    classification: 'NSCU_STATUTORY',
    accountId: 'acc_audit_fee',
    accountName: 'Audit & NSCU Affiliation Fee',
    accountCode: '5130',
    paymentMode: 'UNKNOWN',
    memberId: null,
    memberName: null,
    projectId: null,
    projectName: null,
    stockItem: null,
    status: 'NEEDS_REVIEW',
    reviewNotes: ['Nagaland State Co-operative Union fee. Payment mode UNKNOWN.'],
    paymentModeWarning: true,
    migrationBatchId: MIGRATION_BATCH_ID,
  },
]

/* Initialize unique IDs */
export function getInitialMigrationRows(): HistoricalSourceRow[] {
  return rawHistoricalRows.map(r => ({
    ...r,
    id: `mig_row_${r.slno}`,
  }))
}

/* ── Compute side-by-side reconciliation (Part 13 & 14) ── */
export function computeReconciliationSummary(
  rows: HistoricalSourceRow[],
  transactions: Transaction[]
): HistoricalReconciliationSummary {
  const calculatedReceipts = Math.round(rows.reduce((s, r) => s + (r.sourceReceipt || 0), 0) * 100) / 100
  const calculatedPayments = Math.round(rows.reduce((s, r) => s + (r.sourcePayment || 0), 0) * 100) / 100
  const calculatedClosingBalance = Math.round((calculatedReceipts - calculatedPayments) * 100) / 100

  const receiptsDifference = Math.round((calculatedReceipts - SOURCE_STATED_TOTALS.receipts) * 100) / 100
  const paymentsDifference = Math.round((calculatedPayments - SOURCE_STATED_TOTALS.payments) * 100) / 100
  const closingBalanceDifference = Math.round((calculatedClosingBalance - SOURCE_STATED_TOTALS.closingBalance) * 100) / 100

  const importedCount = rows.filter(r => r.status === 'IMPORTED').length
  const mappedCount = rows.filter(r => r.status === 'MAPPED').length
  const needsReviewCount = rows.filter(r => r.status === 'NEEDS_REVIEW').length
  const approvedCount = rows.filter(r => r.status === 'APPROVED').length
  const postedCount = rows.filter(r => r.status === 'POSTED').length
  const errorCount = rows.filter(r => r.status === 'RECONCILIATION_ERROR').length

  // Filter posted transactions for this migration batch
  const batchTxs = transactions.filter(t => t.migrationBatchId === MIGRATION_BATCH_ID)
  let totalDebit = 0
  let totalCredit = 0
  batchTxs.forEach(t => {
    t.lines.forEach(l => {
      totalDebit += l.debit || 0
      totalCredit += l.credit || 0
    })
  })

  const trialBalanceDifference = totalDebit - totalCredit
  const trialBalanceBalanced = Math.abs(trialBalanceDifference) < 0.01

  return {
    totalSourceRows: rows.length,
    importedCount,
    mappedCount,
    needsReviewCount,
    approvedCount,
    postedCount,
    errorCount,
    sourceStatedReceipts: SOURCE_STATED_TOTALS.receipts,
    calculatedReceipts,
    receiptsDifference,
    sourceStatedPayments: SOURCE_STATED_TOTALS.payments,
    calculatedPayments,
    paymentsDifference,
    sourceStatedClosingBalance: SOURCE_STATED_TOTALS.closingBalance,
    calculatedClosingBalance,
    closingBalanceDifference,
    totalPostedDebit: totalDebit,
    totalPostedCredit: totalCredit,
    trialBalanceBalanced,
    trialBalanceDifference,
  }
}

/* ── Validation for Approval (Part 19: Approve All Valid strict conditions) ── */
export function isRowValidForApproval(row: HistoricalSourceRow): { valid: boolean; reason?: string } {
  if (row.status === 'POSTED') {
    return { valid: false, reason: 'Row has already been posted to live books.' }
  }
  if (!row.accountId) {
    return { valid: false, reason: 'Chart of Accounts mapping is missing.' }
  }
  if (row.paymentMode === 'UNKNOWN') {
    return { valid: false, reason: 'Payment mode is UNKNOWN (requires resolution to Cash, NSCB, SBI, or Online).' }
  }
  if (row.dateWarning && !row.correctedDate && row.sourceDate === '04-05-2026') {
    return { valid: false, reason: 'Date anomaly requires explicit review (Part 15).' }
  }
  if (row.sourceReceipt === null && row.sourcePayment === null) {
    return { valid: false, reason: 'Source row has no receipt or payment amount.' }
  }
  return { valid: true }
}

/* ── Convert an Approved Migration Row into a Double-Entry Central Transaction (Part 20) ── */
export function buildTransactionFromApprovedRow(
  row: HistoricalSourceRow,
  existingTransactions: Transaction[],
  accounts: Account[]
): Transaction {
  const isReceipt = (row.sourceReceipt || 0) > 0
  const amount = isReceipt ? (row.sourceReceipt || 0) : (row.sourcePayment || 0)
  const voucherType = isReceipt ? 'RECEIPT' : 'PAYMENT'
  const effectiveDate = row.correctedDate || row.sourceDate

  const voucherNo = generateNextVoucherNo(voucherType, existingTransactions)

  // Determine cash/bank account based on resolved payment mode
  let assetAccountId = 'acc_cash'
  let assetAccountName = 'Cash in Hand'

  if (row.paymentMode === 'NSCB') {
    assetAccountId = 'acc_nstcb'
    assetAccountName = 'Bank – NSCB (Nagaland State Co-op Bank)'
  } else if (row.paymentMode === 'SBI') {
    assetAccountId = 'acc_sbi'
    assetAccountName = 'Bank – SBI'
  } else if (row.paymentMode === 'UPI_ONLINE') {
    assetAccountId = 'acc_nstcb' // Online routed through primary cooperative bank
    assetAccountName = 'Bank – NSCB (Online / UPI)'
  }

  const oppositeAccountId = row.accountId || (isReceipt ? 'acc_sales' : 'acc_stationery')
  const foundAcc = accounts.find(a => a.id === oppositeAccountId)
  const oppositeAccountName = foundAcc ? foundAcc.name : (row.accountName || 'Historical Nominal Account')

  // Double entry lines
  const lines = isReceipt
    ? [
        {
          id: `l_${row.id}_dr`,
          accountId: assetAccountId,
          accountName: assetAccountName,
          debit: amount,
          credit: 0,
          description: `Historical Receipt: ${row.sourceParticular}`,
          memberId: row.memberId || undefined,
          memberName: row.memberName || undefined,
          projectId: row.projectId || undefined,
        },
        {
          id: `l_${row.id}_cr`,
          accountId: oppositeAccountId,
          accountName: oppositeAccountName,
          debit: 0,
          credit: amount,
          description: row.sourceParticular,
          memberId: row.memberId || undefined,
          memberName: row.memberName || undefined,
          projectId: row.projectId || undefined,
        },
      ]
    : [
        {
          id: `l_${row.id}_dr`,
          accountId: oppositeAccountId,
          accountName: oppositeAccountName,
          debit: amount,
          credit: 0,
          description: row.sourceParticular,
          projectId: row.projectId || undefined,
        },
        {
          id: `l_${row.id}_cr`,
          accountId: assetAccountId,
          accountName: assetAccountName,
          debit: 0,
          credit: amount,
          description: `Historical Payment: ${row.sourceParticular}`,
          projectId: row.projectId || undefined,
        },
      ]

  const val = validateDoubleEntry(lines)
  if (!val.valid) {
    throw new Error(`Migration row ${row.slno} failed double entry: ${val.error}`)
  }

  const tx: Transaction = {
    id: `tx_hist_mig_${row.slno}`,
    voucherNo,
    date: effectiveDate,
    type: voucherType,
    category: row.classification,
    narration: `${row.sourceParticular} (Migrated from Day Book Page ${row.sourcePage}, Sl.No ${row.sourceRowNumber})`,
    amount,
    paymentMode: row.paymentMode === 'UNKNOWN' ? 'CASH' : row.paymentMode,
    memberId: row.memberId || undefined,
    memberName: row.memberName || undefined,
    projectId: row.projectId || undefined,
    status: 'POSTED',
    lines,
    createdAt: new Date().toISOString(),
    migrationBatchId: MIGRATION_BATCH_ID,
    sourceDocument: row.sourceDocument,
    sourceRowNumber: row.sourceRowNumber,
  }

  return tx
}
